apiVersion: v1
kind: Pod
metadata:
  name: default-testpod
spec:
  containers:
    - name: testpod
      image: k8s.gcr.io/pause:2.0
---
apiVersion: v1
kind: Pod
metadata:
  name: my-scheduler-testpod
spec:
  schedulerName: my-scheduler
  containers:
    - name: testpod
      image: k8s.gcr.io/pause:2.0