apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: my-scheduler
    plugins:
      filter:
        enabled:
          - name: TopologyAffinity
      unreserve:
        enabled:
          - name: TopologyAffinity
